timesheet/backend/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeGerenciarAtividadesView.as_view(), name='atividades'),
]

timesheet/backend/setup/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

timesheet/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('api/', include('backend.api.urls')),
    path('', include('backend.login.urls'), name='login_page'),
    path('atividades/', include('backend.base.urls'))
]

timesheet/backend/api/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Cliente, RegistroAtividade, Servico, Atividade

class RegistroAtividadeForm(forms.ModelForm):
    class Meta:
        model = RegistroAtividade
        fields = ['cliente', 'servico', 'atividade']

User = get_user_model()
class FiltroRelatorioForm(forms.Form):
    colaborador = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), required=False)
    servico = forms.ModelChoiceField(queryset=Servico.objects.all(), required=False)
    atividade = forms.ModelChoiceField(queryset=Atividade.objects.all(), required=False)
    data_inicial = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    data_final = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=False)

timesheet/backend/base/views.py
import requests
from django.conf import settings
from django.shortcuts import render, redirect
from django.utils.timezone import localdate
from django.core.paginator import Paginator
from django.views import View
from backend.api.forms import RegistroAtividadeForm
from backend.api.models import RegistroAtividade

class HomeGerenciarAtividadesView(View):

    def get_context_data(self, user):
        """
        Recupera os dados necessários para o contexto do template via API,
        aplicando filtro de grupos (setores) do usuário.
        """
        # URLs das APIs separadas
        api_url_clientes = f"http://127.0.0.1:8000/api/get-api/cliente/"
        api_url_servicos = f"http://127.0.0.1:8000/api/get-api/servico/"
        api_url_atividades = f"http://127.0.0.1:8000/api/get-api/atividade/"
        print("Requisitando APIs:", api_url_clientes, api_url_servicos, api_url_atividades)

        # Faz as requisições para cada API
        try:
            response_clientes = requests.get(api_url_clientes)
            response_clientes.raise_for_status()
            clientes = response_clientes.json()
            
            response_servicos = requests.get(api_url_servicos)
            response_servicos.raise_for_status()
            servicos = response_servicos.json()
            
            response_atividades = requests.get(api_url_atividades)
            response_atividades.raise_for_status()
            atividades = response_atividades.json()

            # Filtro com base nos grupos do usuário
            grupos_usuario = user.groups.all()

            # Filtro dos dados para clientes, serviços e atividades
            clientes = [cliente for cliente in clientes if any(grupo.id in cliente['setor'] for grupo in grupos_usuario)]
            servicos = [servico for servico in servicos if any(grupo.id in servico['setor'] for grupo in grupos_usuario)]
            atividades = [atividade for atividade in atividades if any(grupo.id in atividade['setor'] for grupo in grupos_usuario)]
            
        except requests.exceptions.RequestException as e:
            print(f"Erro ao acessar a API: {e}")
            clientes = []
            servicos = []
            atividades = []

        # Lógica de controle de permissões de admin
        is_admin = user.groups.filter(name='admin').exists()

        return {
            'clientes': clientes,
            'servicos': servicos,
            'atividades': atividades,
            'is_admin': is_admin,
        }

    def calcular_total_duracao(self, atividades_usuario):
        """
        Calcula a duração total das atividades e formata em horas, minutos e segundos.
        """
        total_duracao = sum(
            (atividade.data_final - atividade.data_inicial).total_seconds()
            for atividade in atividades_usuario if atividade.data_final and atividade.data_inicial
        )
        
        # Converte os segundos totais em horas, minutos e segundos
        horas = total_duracao // 3600
        minutos = (total_duracao % 3600) // 60
        segundos = total_duracao % 60

        # Retorna a duração formatada
        return f"{int(horas)}h {int(minutos)}m {int(segundos)}s"


    def get(self, request):
        """
        Exibe o formulário e lista as atividades do colaborador.
        """
        user = request.user
        context = self.get_context_data(user)

        # Lista as atividades do usuário no dia atual
        atividades_usuario = RegistroAtividade.objects.filter(
            data_inicial__date=localdate(), colaborador=user
        ).order_by('-data_inicial')

        # Paginação
        paginator = Paginator(atividades_usuario, 9)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        # Atualiza o contexto com a duração formatada
        context.update({
            'form': RegistroAtividadeForm(),
            'page_obj': page_obj,
            'total_duracao': self.calcular_total_duracao(atividades_usuario),  # Passando a duração formatada
        })

        return render(request, 'base/minhas_atividades.html', context)

    def post(self, request):
        """
        Processa o registro de uma nova atividade.
        """
        user = request.user

        # Registra uma nova atividade usando o formulário
        form = RegistroAtividadeForm(request.POST)
        if form.is_valid():
            atividade = form.save(commit=False)
            atividade.colaborador = user
            atividade.save()
            return redirect('atividades')

        # Em caso de erro, reexibe o formulário com os dados inseridos
        context = self.get_context_data(user)
        atividades_usuario = RegistroAtividade.objects.filter(
            data_inicial__date=localdate(), colaborador=user
        ).order_by('-data_inicial')

        # Paginação
        paginator = Paginator(atividades_usuario, 9)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        # Atualiza o contexto com a duração formatada
        context.update({
            'form': form,
            'page_obj': page_obj,
            'total_duracao': self.calcular_total_duracao(atividades_usuario),  # Passando a duração formatada
        })

        return render(request, 'base/minhas_atividades.html', context)

timesheet/frontend/templates/base/add.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dome Timesheet</title>
    <script src="https://kit.fontawesome.com/6617ed4ead.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="{% static 'img/Fav.svg' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/NavAside.css' %}">
    <link rel="stylesheet" href="{% static 'css/add.css' %}">
</head>
<body>
    <header>
        <nav>
            <!-- Parte Esquerda Nav -->
            <div class="div-nav-left">
                <div class="div-menu-left">
                    <h1>Adicionar Novo</h1>
                </div>   
            </div>
            <!-- Parte Direita Nav -->
            <div class="div-nav-right">
                <div class="div-user-nav">
                    <ul>
                        <li><h1>Olá, {{ user.username|capfirst }}</h1></li>
                        <!-- Formulário Sair-->
                        <form action="{% url 'logout' %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" id="btn-sair">
                                <i class="fa-solid fa-right-from-bracket" id="exit-menu"></i>
                            </button>
                        </form>
                    </ul>  
                </div>
            </div>
        </nav>
    </header>

    <!-- Aside -->
    <aside>
        <a href="{% url 'home' %}"><img src="{% static 'img/Branca.svg' %}" alt="o-dome" id="logo-dome"></a>
        <div class="aside-content">
            <ul class="aside-ul-content">
                <li><a href="{% url 'add' %}"><i class="fa-solid fa-plus" id="soma-icon"></i></a></li>
                <li><a href="{% url 'minhas_atividades' %}"><i class="fa-solid fa-business-time"></i></a></li>
                
                {% if user.is_authenticated %}
                {% if is_admin %}
                <li><a href="{% url 'gerar_relatorio' %}"><i class="fa-solid fa-cloud-arrow-up"></i></a></li>
                {% endif %}
                {% endif %}
                
            </ul>
        </div>
    </aside>

    <!-- Conteúdo -->
    <main>
        <div class="main-box">
            <div class="main-content">
                <h1>Nova Atividade</h1>
                
                <!-- Bloco para mensagens -->
                {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                            <div class="alert">{{ message }}</div>
                        {% endfor %}
                    </div>
                {% endif %}

                <form method="POST" class="form-add">
                    {% csrf_token %}
                    
                    <label for="id_cliente">Cliente</label>
                    <select name="cliente" id="id_cliente">
                        {% for cliente in clientes %}
                            <option value="{{ cliente.id }}">{{ cliente.nome }}</option>
                        {% endfor %}
                    </select>
                
                    <label for="id_servico">Serviço</label>
                    <select name="servico" id="id_servico">
                        {% for servico in servicos %}
                            <option value="{{ servico.id }}">{{ servico.nome }}</option>
                        {% endfor %}
                    </select>
                
                    <label for="id_atividade">Atividade</label>
                    <select name="atividade" id="id_atividade">
                        {% for atividade in atividades %}
                            <option value="{{ atividade.id }}">{{ atividade.nome }}</option>
                        {% endfor %}
                    </select>
                
                    <button class="botao-add-form" type="submit">Registrar Atividade</button>
                </form>
                
            </div>
        </div>
    </main>

    <script type="application/json" id="atividades_ativas">
        {{ atividades_ativas|json_script:"atividades_ativas" }}
    </script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const form = document.querySelector('.form-add');

            // Função para verificar se já existe uma atividade ativa
            function verificarAtividadeAtiva() {
                const atividadesAtivas = JSON.parse(document.getElementById('atividades_ativas').textContent);
                return atividadesAtivas.length > 0;
            }

            form.addEventListener('submit', function(event) {
                if (verificarAtividadeAtiva()) {
                    alert('Você já possui uma atividade ativa. Finalize-a antes de criar uma nova.');
                    event.preventDefault(); // Impede o envio do formulário
                }
            });
        });
    </script>

</body>
</html>

timesheet/frontend/templates/base/minhas_atividades.html
{% extends 'theme/base.html' %}
{% load static %}
{% block content %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'base/adicionar_atividade.css' %}">
<link rel="stylesheet" href="{% static 'base/table.css' %}">
<link rel="stylesheet" href="{% static 'base/minhas_atividades.css' %}">
<link rel="stylesheet" href="{% static 'base/modal.css' %}">
{% endblock %}

<table>
    <thead>
        <tr class="atividade-topo">
            <!-- Linha de botão Adicionar Atividade -->
            <th colspan="6" class="top_buttons">
        
                <!--BOTÃO MODAL E FINALIZAR ATIVIDADE-->

                <div class="atividade-right">
                    <div class="atividade-left">

                        <form method="POST" class="form-add">
                            {% csrf_token %}
                        
                            <!-- Campo Cliente -->
                            <select name="cliente" id="id_cliente">
                                <option value="" disabled selected>Selecione o Cliente</option>
                                {% for cliente in clientes %}
                                    <option value="{{ cliente.id }}">{{ cliente.nome }}</option>
                                {% endfor %}
                            </select>
                        
                            <!-- Campo Serviço -->
                            <select name="servico" id="id_servico">
                                <option value="" disabled selected>Selecione o Serviço</option>
                                {% for servico in servicos %}
                                    <option value="{{ servico.id }}">{{ servico.nome }}</option>
                                {% endfor %}
                            </select>
                        
                            <!-- Campo Atividade -->
                            <select name="atividade" id="id_atividade">
                                <option value="" disabled selected>Selecione a Atividade</option>
                                {% for atividade in atividades %}
                                    <option value="{{ atividade.id }}">{{ atividade.nome }}</option>
                                {% endfor %}
                            </select>
                        
                            <button class="botao-add-form" type="submit">Registrar Atividade</button>
                        </form>

                        {% for atividade in page_obj %}
                            {% if atividade.ativo %}
                                <button 
                                    class="btn-finalizar-atividade" 
                                    data-id="{{ atividade.id }}" 
                                    onclick="finalizarAtividadePorElemento(this)">
                                    Finalizar Atividade
                                </button>
                            {% endif %}
                        {% endfor %}

                    </div>
                </div>
            </th>
        </tr>
        
        
        <tr>
            <th>Cliente</th>
            <th>Serviço</th>
            <th>Atividade</th>
            <th>Data Inicial</th>
            <th>Data Final</th>
            <th>Duração</th>
        </tr>
    </thead>

    <tbody>
        {% for atividade in page_obj %}
        <tr>
            <td>{{ atividade.cliente }}</td>
            <td>{{ atividade.servico }}</td>
            <td>{{ atividade.atividade }}</td>  
            <td>{{ atividade.data_inicial|date:"d/m/Y H:i"|default:"-" }}</td>

            <!--RELAÇÃO ATIVIDADE ABERTA/DURAÇÃO -->
            <td id="atividade_ativo_{{ atividade.id }}" style="display: none;">{{ atividade.ativo }}</td>
            <td id="data_final_{{ atividade.id }}">
                {{ atividade.data_final|date:"d/m/Y H:i"|default:"Atividade Ativa" }}
            </td>
            <td id="duracao_{{ atividade.id }}">
                {{ atividade.duracao_formatada }}
            </td>
            <td id="data_inicial_{{ atividade.id }}" style="display: none;">
                {{ atividade.data_inicial|date:"Y-m-d H:i:s" }}
            </td>
            
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr style="background-color: transparent;">
            <td colspan="5" style="text-align: right; font-weight: bold;">Total de Horas:</td>
            <td>
                {{ total_duracao }}
            </td>
        </tr>
    </tfoot>
</table>




<!--Paginador-->
<div class="pagination">
    <ul class="pagination-list">
        {% if page_obj.has_previous %}
            <li><a href="?page=1">&laquo; Primeira</a></li>
            <li><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
        {% else %}
            <li class="disabled">&laquo; Primeira</li>
            <li class="disabled">Anterior</li>
        {% endif %}

        <li class="current">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</li>

        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
            <li><a href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li>
        {% else %}
            <li class="disabled">Próxima</li>
            <li class="disabled">Última &raquo;</li>
        {% endif %}
    </ul>
</div>




<!-- JAVA SCRIPT -->

<script>

    // SCRF TOKEN

    function getCSRFToken() {
    const name = 'csrftoken';
    const cookies = document.cookie.split(';');
    for (let cookie of cookies) {
        cookie = cookie.trim();
        if (cookie.startsWith(name + '=')) {
            return cookie.slice(name.length + 1);
        }
    }
    return null; // Se o token não for encontrado
}


    // Referências para os selects
    const clienteSelect = document.getElementById('id_cliente');
    const servicoSelect = document.getElementById('id_servico');
    const atividadeSelect = document.getElementById('id_atividade');

    // Função para preencher um select com opções
    function preencherSelect(selectElement, data, placeholder) {
        // Limpa o select e adiciona um placeholder
        selectElement.innerHTML = `<option value="" disabled selected>${placeholder}</option>`;
        data.forEach(item => {
            const option = document.createElement('option');
            option.value = item.id; // ID do item
            option.textContent = item.nome; // Nome do item
            selectElement.appendChild(option);
        });
        selectElement.disabled = false; // Desbloqueia o select
    }

        // Evento para carregar serviços ao selecionar um cliente
    clienteSelect.addEventListener('change', function () {
        const clienteId = this.value; // Obtém o ID do cliente selecionado

        // Reseta os selects de serviços e atividades
        preencherSelect(servicoSelect, [], 'Selecione o Serviço');
        preencherSelect(atividadeSelect, [], 'Selecione a Atividade');
        servicoSelect.disabled = true;
        atividadeSelect.disabled = true;

        // Requisição para buscar os serviços do cliente
        fetch(`/api/get-api/servico/?clientes=${clienteId}`)
            .then(response => {
                if (!response.ok) throw new Error('Erro ao carregar os serviços.');
                return response.json();
            })
            .then(data => {
                if (data && Array.isArray(data)) {
                    preencherSelect(servicoSelect, data, 'Selecione o Serviço');
                }
            })
            .catch(error => {
                console.error('Erro ao carregar serviços:', error);
            });
    });

    // Evento para carregar atividades ao selecionar um serviço
    servicoSelect.addEventListener('change', function () {
        const servicoId = this.value; // Obtém o ID do serviço selecionado

        // Reseta o select de atividades
        preencherSelect(atividadeSelect, [], 'Selecione a Atividade');
        atividadeSelect.disabled = true;

        // Requisição para buscar as atividades do serviço
        fetch(`/api/get-api/atividade/?servicos=${servicoId}`)
            .then(response => {
                if (!response.ok) throw new Error('Erro ao carregar as atividades.');
                return response.json();
            })
            .then(data => {
                if (data && Array.isArray(data)) {
                    preencherSelect(atividadeSelect, data, 'Selecione a Atividade');
                }
            })
            .catch(error => {
                console.error('Erro ao carregar atividades:', error);
            });
    });


</script>

<script>
    function iniciarContagem() {
        // Pega todos os elementos de hora de início
        const atividades = document.querySelectorAll('[id^="data_inicial_"]');
        
        atividades.forEach(function(element) {
            const atividadeId = element.id.split('_')[2]; // Ex: hora_inicio_1 => id = 1
            const horaInicio = element.innerText; // Hora de início da atividade
            const horaInicioDate = new Date(horaInicio); // Converte para objeto Date
            
            // Verifica se a atividade está ativa (usando a variável ativo)
            const ativo = document.getElementById(`atividade_ativo_${atividadeId}`)?.innerText === 'True'; 
            if (!ativo) {
                // Se a atividade não está ativa, não inicia o temporizador
                return;
            }
    
            // Função que será chamada a cada segundo
            const intervalId = setInterval(function() {
                // Verifica se a atividade está ativa
                const ativo = document.getElementById(`atividade_ativo_${atividadeId}`)?.innerText === 'True'; 
                if (!ativo) {
                    clearInterval(intervalId); // Se a atividade não está ativa, para o contador
                    return;
                }
    
                // Pega a hora atual
                const tempoAtual = new Date();
                
                // Calcula a diferença entre o tempo atual e a hora de início
                const diffMilliseconds = tempoAtual - horaInicioDate;
                
                // Converte a diferença em segundos, minutos e horas
                const diffSeconds = Math.floor(diffMilliseconds / 1000); // Milissegundos para segundos
                const diffMinutes = Math.floor(diffSeconds / 60); // Segundos para minutos
                const diffHours = Math.floor(diffMinutes / 60); // Minutos para horas
                const remainingMinutes = diffMinutes % 60; // Minutos restantes
                const remainingSeconds = diffSeconds % 60; // Segundos restantes
    
                // Atualiza a duração na interface
                const duracaoElement = document.getElementById(`duracao_${atividadeId}`);
                duracaoElement.innerText = `${diffHours}h ${remainingMinutes}m ${remainingSeconds}s`;
            }, 1000);  // Atualiza a cada 1 segundo
        });
    }
    
    // Inicia a contagem assim que a página for carregada
    window.onload = iniciarContagem;
    </script>

<script>

function finalizarAtividadePorElemento(buttonElement) {
    // Desabilita o botão para impedir múltiplos cliques
    buttonElement.disabled = true;

    const atividadeId = buttonElement.getAttribute("data-id");

    fetch(`/api/get-api/finalizar_atividade/${atividadeId}/`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': getCSRFToken()
        },
        body: JSON.stringify({id: atividadeId})
    })
    .then(response => {
        if (!response.ok) {
            throw new Error('Erro na requisição: ' + response.status);
        }
        return response.json();
    })
    .then(data => {
        if (data.success) {
            const dataFimElement = document.getElementById(`data_final_${atividadeId}`);
            dataFimElement.innerText = data_final || 'Finalizado';  // Atualiza a data de fim

            // Remover o botão e colocar um status "Finalizado"
            buttonElement.remove();
            const statusElement = buttonElement.parentElement;
            statusElement.innerHTML = '<span>Atividade Finalizada</span>';

            // Atualiza a página (recarrega)
            location.reload();  // Recarrega a página para garantir que o tempo pare
        } else {
            const statusElement = buttonElement.parentElement;
            statusElement.innerHTML = '<span>Falha ao finalizar a atividade. Tente novamente.</span>';
        }
    })
    .catch(error => {
        console.error('Erro:', error);
        const statusElement = buttonElement.parentElement;
        statusElement.innerHTML = '<span>Ocorreu um erro inesperado. Tente novamente.</span>';
        location.reload();
    })
    .finally(() => {
        buttonElement.disabled = false;
        location.reload();
    });
}
</script>

{% endblock %}